rename 's/190.14.254.237/links_domain=19014254237_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/airport/links_domain=airport_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/amsterdammuseum/links_domain=amsterdammuseum_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/bl-example.nt.bz2/links_domain=blexamplentbz2_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/bookmashup/links_domain=bookmashup_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/bricklink/links_domain=bricklink_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/cordis/links_domain=cordis_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/data.linkedmdb.org/links_domain=datalinkedmdborg_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/data.logainm.ie/links_domain=datalogainmie_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/dati.camera.it/links_domain=daticamerait_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/dati.isprambiente.it/links_domain=datiisprambienteit_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/dblp/links_domain=dblp_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/dbtune.org/links_domain=dbtuneorg_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/diseasome/links_domain=diseasome_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/dnb/links_domain=dnb_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/drugbank/links_domain=drugbank_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/eunis.eea.europa.eu/links_domain=euniseeaeuropaeu_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/eurostat.linked-statistics.org/links_domain=eurostatlinkedstatisticsorg_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/eurostat_wbsg/links_domain=eurostatwbsg_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/factbook/links_domain=factbook_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/gadm.geovocab.org/links_domain=gadmgeovocaborg_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/geospecies/links_domain=geospecies_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/gho/links_domain=gho_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/gutenberg/links_domain=gutenberg_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/gwn-ili/links_domain=gwnili_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/italian_public_schools/links_domain=italianpublicschools_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/jrc_names/links_domain=jrcnames_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/learning-provider.data.ac.uk/links_domain=learningproviderdataacuk_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/linkedgeodata.org/links_domain=linkedgeodataorg_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/linked_web_apis/links_domain=linkedwebapis_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/lmdb/links_domain=lmdb_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/lobid.org/links_domain=lobidorg_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/manifestation/links_domain=manifestation_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/nytimes/links_domain=nytimes_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/opencyc/links_domain=opencyc_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/openei.org/links_domain=openeiorg_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/organisation/links_domain=organisation_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/rdfdata.eionet.europa.eu/links_domain=rdfdataeioneteuropaeu_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/revyu/links_domain=revyu_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/sider/links_domain=sider_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/tcm/links_domain=tcm_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/transparency.270a.info/links_domain=transparency270ainfo_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/umbel/links_domain=umbel_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/uscensus/links_domain=uscensus_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/viaf.org/links_domain=viaforg_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/wikicompany/links_domain=wikicompany_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/wl-example.nt.bz2/links_domain=wlexamplentbz2_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/worldbank.270a.info/links_domain=worldbank270ainfo_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/www4.wiwiss.fu-berlin.de/links_domain=www4wiwissfuberlinde_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/www.bbc.co.uk/links_domain=wwwbbccouk_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/www.bbc.co.uk.things/links_domain=wwwbbccoukthings_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/www.geonames.org/links_domain=wwwgeonamesorg_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/www.grid.ac/links_domain=wwwgridac_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/www.springernature.com/links_domain=wwwspringernaturecom_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/www.w3.org/links_domain=wwww3org_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/yago/links_domain=yago_lang=en.nt.bz2/' */dbpedia.org/*  
rename 's/zbw.eu/links_domain=zbweu_lang=en.nt.bz2/' */dbpedia.org/*  
